[package]
name = "exec"
version = "0.1.0"
edition = "2021"

[dependencies]
lua_parser = { version = "0.1.0", path = "../parser", features = ["diag"] }
codespan-reporting = { version = "0.11" }

[features]
default = []
32bit = ["lua_parser/32bit"]
