[package]
name = "tokenizer"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan-reporting = { version = "0.11", optional = true }

[features]
default = []
32bit = []
diag = ["dep:codespan-reporting"]
